function Stage3anonymized = importOberijeEtAlData(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   STAGE3ANONYMIZED = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   STAGE3ANONYMIZED = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   Stage3anonymized = importfile('Stage3_anonymized.csv', 2, 549);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/06/22 09:07:22

%% Initialize variables.
delimiter = ';';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\.]*)+[\,]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\.]*)*[\,]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers=='.');
                thousandsRegExp = '^\d+?(\.\d{3})*\,{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator;
                numbers = strrep(numbers, '.', '');
                numbers = strrep(numbers, ',', '.');
                numbers = textscan(numbers, '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
Stage3anonymized = table;
Stage3anonymized.study_id = cell2mat(raw(:, 1));
Stage3anonymized.gender = cell2mat(raw(:, 2));
Stage3anonymized.age = cell2mat(raw(:, 3));
Stage3anonymized.who3g = cell2mat(raw(:, 4));
Stage3anonymized.bmi = cell2mat(raw(:, 5));
Stage3anonymized.fev1pc_t0 = cell2mat(raw(:, 6));
Stage3anonymized.dumsmok2 = cell2mat(raw(:, 7));
Stage3anonymized.t_ct_loc = cell2mat(raw(:, 8));
Stage3anonymized.hist4g = cell2mat(raw(:, 9));
Stage3anonymized.countpet_all6g = cell2mat(raw(:, 10));
Stage3anonymized.countpet_mediast6g = cell2mat(raw(:, 11));
Stage3anonymized.tstage = cell2mat(raw(:, 12));
Stage3anonymized.nstage = cell2mat(raw(:, 13));
Stage3anonymized.stage = cell2mat(raw(:, 14));
Stage3anonymized.timing = cell2mat(raw(:, 15));
Stage3anonymized.group = cell2mat(raw(:, 16));
Stage3anonymized.yearrt = cell2mat(raw(:, 17));
Stage3anonymized.eqd2 = cell2mat(raw(:, 18));
Stage3anonymized.ott = cell2mat(raw(:, 19));
Stage3anonymized.gtv1 = cell2mat(raw(:, 20));
Stage3anonymized.tumorload_total = cell2mat(raw(:, 21));
Stage3anonymized.survmonth = cell2mat(raw(:, 22));
Stage3anonymized.survyear = cell2mat(raw(:, 23));
Stage3anonymized.deadstat = cell2mat(raw(:, 24));

