function localSimulation(maxIter,runId,siteIds,sparqlToken,sparqlProxy,dataProxyType,codePath,dataPath,userInputFilePath,simulationLocationPath,resultPath)
%% preparation: create path strings etc.
numberOfSites = numel(siteIds);
masterOutputFileName = 'input_'; % always followed by the site id and '.txt' (added in a row below this)
userInputFileName = 'UserInputFile.txt';
resultFileName = 'Result.txt';
siteOutputFileName = 'DistOutput_'; % always followed by the site id and '.txt' (added in a row below this)

masterSourceCodePath = fullfile(codePath,'master'); % the location of the master code
genericSourceCodePath = fullfile(codePath,'SourceCode', 'generic'); % the location of the generic code in the simulation
masterPath = fullfile(simulationLocationPath,'master'); % the location of the master simulation
masterUserInputPath = fullfile(masterPath,userInputFileName); % the location of the user input file on the master (to be copied there before simulation starts)
masterLogFilePath = fullfile(masterPath, 'log.txt');

siteSourceCodePath = fullfile(codePath,'site'); % the location of the site code
for ii = 1:numberOfSites
    masterOutputPathCell{ii} = fullfile(masterPath,[masterOutputFileName num2str(siteIds(ii)) '.txt']);
    sitePathCell{ii} = fullfile(simulationLocationPath,['site' num2str(siteIds(ii))]); % the location of the site simulation
    siteDataPathCell{ii} = fullfile(dataPath,['site' num2str(siteIds(ii))]); % the location of the site data (this data is copied to Simulation Space before start of simulation)
    siteInputPathCell{ii} = fullfile(sitePathCell{ii},[masterOutputFileName num2str(siteIds(ii)) '.txt']); % the location of the master output when copied for site ii
    siteOutputPathCell{ii} = fullfile(sitePathCell{ii},[siteOutputFileName num2str(siteIds(ii)) '.txt']); % the location of the output of site ii on site ii itself
    masterInputPathCell{ii} = fullfile(masterPath,[siteOutputFileName num2str(siteIds(ii)) '.txt']); % the location of the output of site ii when copied for the master
    siteLogFilePathCell{ii} = fullfile(sitePathCell{ii}, 'log.txt');
end
%% delete old simulation folders and create new empty master/site folders
if exist(simulationLocationPath,'dir') == 7 % if old simulation folder exists, delete it
    sink = rmdir(simulationLocationPath,'s');
end
mkdir(simulationLocationPath);


mkdir(masterPath);
for ii = 1:numberOfSites
    mkdir(sitePathCell{ii});
end
%% deploy code on master and sites: copied from portal_code to simulation folders
masterSourceDir = dir(masterSourceCodePath);
masterSourceDir = deleteDotsInDir(masterSourceDir);
batchCopyFiles({masterSourceDir.name},masterSourceCodePath,masterPath,0);

genericSourceDir = dir(genericSourceCodePath);
genericSourceDir = deleteDotsInDir(genericSourceDir);
batchCopyFiles({genericSourceDir.name},genericSourceCodePath,masterPath,0);

siteSourceDir = dir(siteSourceCodePath);
siteSourceDir = deleteDotsInDir(siteSourceDir);
for ii = 1:numberOfSites
    batchCopyFiles({siteSourceDir.name},siteSourceCodePath,sitePathCell{ii},0);
    batchCopyFiles({genericSourceDir.name},genericSourceCodePath,sitePathCell{ii},0);
end

%% deploy data on sites
for ii = 1:numberOfSites
    siteDataDir = dir(siteDataPathCell{ii});
    siteDataDir = deleteDotsInDir(siteDataDir);
    batchCopyFiles({siteDataDir.name},siteDataPathCell{ii},sitePathCell{ii},0);
end

%% deploy user input file
copyfile(userInputFilePath,masterUserInputPath);

%% simulate DL
Abort = 0;
for ii = 1:maxIter
    display(['Iteration ' num2str(ii)])
    
    %% run master
    display('Run code on master')
    cd(masterPath); % change current directory to site simulation location
    mainMaster(num2str(runId),num2str(ii),masterPath,masterPath,masterPath,num2str(Abort),num2str(siteIds),masterUserInputPath,masterLogFilePath);
    %     execute_algo(inputVars);
    %% check if result file is generated by master. If yes, stop.
    if exist(fullfile(masterPath,resultFileName),'file') == 2
        display('Result file found. Simulation ends.');
        break
    end
    %% run sites
    for siteLoop = 1:numberOfSites
        copyfile(masterOutputPathCell{siteLoop},siteInputPathCell{siteLoop}); % copy files from master to site
        display(['Run code on site ' num2str(siteLoop)]);
        cd(sitePathCell{siteLoop}); % change current directory to site simulation location
        mainSite(num2str(runId),num2str(ii),siteInputPathCell{siteLoop},siteOutputPathCell{siteLoop},sitePathCell{siteLoop},siteLogFilePathCell{siteLoop},sparqlProxy,sparqlToken,dataProxyType);
        % call site algo corresponding to site 'siteLoop'
        copyfile(siteOutputPathCell{siteLoop},masterInputPathCell{siteLoop}); % copy files from site to master
    end
    
end

if exist(fullfile(masterPath,resultFileName),'file') == 2
    % label result file with time and date and copy result file to
    % resultPath
    curTime = datestr(now);
    curTime = strrep(curTime,':','');
    curTime = strrep(curTime,'-','');
    curTime = strrep(curTime,' ','_');
    copyfile(fullfile(masterPath,resultFileName),fullfile(resultPath,['Result' '_' curTime '.txt']));
else
    error('Simulation ended without a result file being generated.')
end
end