clear
clc

%% user input to organize the simulation environment and to fill the function inputs (for mainMaster() and mainSite())
repositoryPath = ''; % the path to the repository
simulationLocationPath = ''; % the path to the folder where the simulation should take place.
resultPath = ''; % the path to the folder where output should be stored

maxIter = 10000; % increase this if you algorithm takes longer. It needs to be at least as large as the value set in the user input file
runId = 1; % this is only important on the portal - here runId has no specific meaning
siteIds = [28 38 78 234 846]; % list the site ids that are involved in the simulation. Ids need to be numeric and listed in a vector.
sparqlToken = '';
sparqlProxy = '';

%% autocomplete paths
codePath = fullfile(repositoryPath,'portal_code'); % the path to the folder where master and site code folders with code are located. 
dataPath = fullfile(repositoryPath,'local_simulation','data'); % the path to the folder where data folders per site are located.
userInputFilePath = fullfile(repositoryPath,'create_user_input_file','userInputFile.txt'); % the path to the user input file

% The folder simulationLocationPath and its contents will be deleted at the start of each
% simulation. DO NOT ASSIGN A VALUABLE FOLDER.

% SiteId needs to be numerical but these site IDs do not need
% to be in any order. You could have 3 sites named 473893, 2748490, and
% 8483677 (if you wanted).

% 
% The codePath folder needs to contain a 'master' and a 'site' folder.
% 'master' and 'site' need to contain all code/files (e.g., scripts, functions,
% executables, .DLLs) necessary to run the algorithm. Data files or files 
% specific for a site's data retrieval should NOT be in here. They should 
% be put into the 'Data' folder (described below).
% Files contained in 'master' will be copied into the 'master' folder of the 
% simulation environment. Files contained in 'site' will be copied to 
% EACH site folder in the simulation environment. 

% The folder 'data' within 'local_simulation' needs to contain a folder for each site with names
% ['Site'num2str(SiteId)]. Place all the files in these subfolders which
% would be at the site (except mainSite.m and its subfunctions). These would be files necessary 
% for retrieving data (except mainSite.m and its subfunctions). If you use the example data
% as provided by the function script_create_example_data.m, you don't need to add another other files
% besides the .mat files generated by script_create_example_data.m. 

% The result file (if generated) will be copied to the folder resultPath at the end of the
% simulation.

localSimulation(maxIter,runId,siteIds,sparqlToken,sparqlProxy,codePath,dataPath,userInputFilePath,simulationLocationPath,resultPath);
